apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s1
provisioner: csi-cinderplugin
parameters:
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - zone1
